### PR TITLE
AUI-1839

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @brunocoelho,

Attached is an update for http://issues.liferay.com/browse/AUI-1839.  I am sending this to you since this removes a file that you changed with https://github.com/liferay/alloy-ui/commit/be6cc519407d0e0f13362921587b4b94a7eae418.

Can you review this change and see if this is advisable or if there is a specific reason why you are overriding the `margin-bottom` values in `.table`?

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @mairatma,

Can you check this pull request as well?  I am not sure if @brunocoelho has had a chance to review this.

Please let me know if you have any questions.  Thanks!

**Comment by mairatma** [comment]
I've looked at this and saw that without this css the datatable demo looks weird, as it has a margin inside the scrollable area of the table. Take a look:
screen shot 2015-01-30 at 10 34 49 am

So that's probably why @brunocoelho added it at the time. I agree that it's best not to override the rules of bootstrap classes directly though, as it will affect other places using it, which is the cause of the bug you're fixing. We need to fix that margin for datatable though, so we should move it to a more specific selector instead, probably `.table-x-scroller .table`, inside `aui-datatable-core-core.css`, since `table-x-scroller` is ours.

@jonmak08, could you do that change and also add the HISTORY.md entry for this? Then you can send the pr to me if you like.

**Comment by jonmak08** [comment]
Hey @mairatma,

I will make the changes and resend you a new pull request for this change.

I will close out this pull request for now.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/mairatma/alloy-ui/pull/159

**Pull request closed without merging**
